name: Health

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes

jobs:
  test:
    name: Health Checks

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with: 
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Setup tenderly 
        run: |
          mkdir ~/.tenderly
          touch ~/.tenderly/config.yaml
          echo "access_key: $TENDERLY_ACCESS_KEY" >> ~/.tenderly/config.yaml
        env:
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}

      - name: Test deployment and network health
        run: pnpm test:health
        env:
          TENDERLY_PROJECT: carbon-temp-forks
          TENDERLY_TEST_PROJECT: carbon-temp-forks
          TENDERLY_USERNAME: bancor
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
